### ISSUE TITLE
Can't run faucet on windows when installed as a project module

### ISSUE THREAD

**Issue by p-v-d-Veeken** [substack/faucet#14]
When faucet is installed as a project dependency, it hangs indefinitely when called directly or through some test command. 

Example:
`node_modules/.bin/faucet` produces just an empty and a blinking cursor in git bash. (haven't tried it in other Windows bash adaptations)

Additional info:
- **OS:** Windows 8.1 64-bit
- **Node version:** v5.0.0
- **npm version:** v3.3.6

**Comment by Elyx0** [comment]
Same issue, I get:
```
./node_modules/.bin/tape -r babel-register tests/*.js | ./node_modules/.bin/faucet
module.js:472
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lx0/testfaucet/node_modules/.bin/faucet:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:804:14)```
