### ISSUE TITLE
faucet command not working on win10

### ISSUE THREAD

**Issue by dbnapp** [substack/faucet#17]
Getting this error when just using `faucet`

```js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\UserName\AppData\Roaming\npm\node_modules\faucet\node_modules\tape\bin\tape ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

```

**Comment by matthiasg** [comment]
it is working here (just looking a little ugly due to missing characters)
